
name: Commitlint

on:
  push:
    branches: ['master']
  pull_request:  
     branches: [ "master" ]

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    name: Check conventional commit lint
    steps:
      - uses: actions/checkout@v4

      - name: Run commitlint
        uses: opensource-nepal/commitlint@v0.2.1