name: Commitlint

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - uses: actions/checkout@v4

      - name: Run commitlint
        uses: opensource-nepal/commitlint@v0.2.1