name: Books CI

on:
  push:
    branches: ['master']
  pull_request:  
     branches: [ "master" ]
     types: submitted

jobs:
  build:
    name : To build for deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
  
      - name: "Replace env variables (dev)"
         uses: danielr1996/envsubst-action@1.0.0
         env:
            APP_ENV: ${{ vars.VITE_APP_API }}
            API_KEY: ${{ secrets.VITE_APP_API }}
         with:
            output: .env
    - name: "Install dependencies and build"
    - run: |
           npm install
           npm run build
           sudo service nginx restart
  
