name: Books CI

on:
  push:
    branches: ['master']
  pull_request:  
     branches: [ "master" ]
     types: submitted

jobs:
  build:
    name : To build for deploy
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      env:
        with:
        VITE_APP_API: ${{secrets.VITE_APP_API}}
        file_name: .env
    -name: Install dependency and build
    - run: |
           npm install
           npm run build
           sudo service nginx restart
  
